# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="honukai"

# Auto start tmux
ZSH_TMUX_AUTOSTART=false

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(tmux gitfast zsh-syntax-highlighting osx brew z)

source $ZSH/oh-my-zsh.sh

# Force mkdir to create intermediate dirs
alias mkdir='mkdir -p'

# Stop auto correcting good commands!
alias vagrant='nocorrect vagrant'

# Force tmux to work with 256 colors.
alias tmux='tmux -2'

# Archiving
alias tarbz2='tar -jcvf'
alias targz='tar -zcvf'
alias untarbz2='tar -jxvf'
alias untargz='tar -zxvf'

# Git
alias gti='git'
alias gs='git status'
alias gc='git commit'
alias ga='git add'
alias gb='git branch'
alias gch='git checkout'
alias gl='git log --pretty=format:"%C(yellow)%h %C(blue)%ad%C(red)%d %C(reset)%s%C(green) [%cn]" --decorate --date=short'
alias yesterday="git log --since '1 day ago' --oneline --author nddery@gmail.com"

# Vim
# Start VIM in "encrypted" mode
alias vimenc="vim -u ~/.vimrc.encrypted -x"

# Update Brew packages (all)
alias brewUpdateAll="brew update --all && brew upgrade `brew outdated` && brew cleanup && brew cask cleanup"

# Launch iOS simulator
alias simulator="open /Applications/Xcode.app/Contents/Developer/Applications/iOS\ Simulator.app"

# Let's go to nom!
alias nom='npm'

# exuberant ctags ftw
alias ctags="`brew --prefix`/bin/ctags"

# Update SPF13-VIM-3
function updateVim() {
  sh <(curl https://j.mp/spf13-vim3 -L)
  cd ~/.vim/bundle/tern_for_vim && npm install
}

# .mov to animated .gif!
# parameters are input output
function movtogif() {
  ffmpeg -i $1 -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=20 > $2
}

# Dev functions - apache and mysql
function startdev() {
  echo "* mysql.server start"
  mysql.server start
  echo "* sudo apachectl start"
  sudo apachectl start
  # echo "* startmongo"
  # startmongo
}

function stopdev() {
  echo "* mysql.server stop"
  mysql.server stop
  echo "* sudo apachectl stop"
  sudo apachectl stop
  # echo "* stopmongo"
  # stopmongo
}

function restartdev() {
  echo "*  mysql.server restart"
  mysql.server restart
  echo "* sudo apachectl restart"
  sudo apachectl restart
}

function startmongo() {
  launchctl load /usr/local/opt/mongodb/homebrew.mxcl.mongodb.plist
}

function stopmongo() {
  launchctl unload /usr/local/opt/mongodb/homebrew.mxcl.mongodb.plist
}

function startmemcache() {
  memcached -m 8 -l 127.0.0.1 -p 11211 -d
}


# Use the existing VIM session if it exists
# Or fallback to normal mvim if no argument is passed
function mvim() {
  if [ -n "$1" ] ; then
    command mvim --remote-silent "$@"
  elif [ -n "$( command mvim --serverlist )" ] ; then
    command mvim --remote-send ":call foreground()<CR>:enew<CR>:<BS>"
  else
    command mvim
  fi
}


# empty all VIM backup/swap/views directory (for when there's some problem
# with arrow keys and...)
function cleanVIM() {
  # directories we'll empty are
  echo "Cleaning ~/.vimbackup/"
  rm -Rf ~/.vimbackup/*
  echo "Cleaning ~/.vimswap/"
  rm -Rf ~/.vimswap/*
  echo "Cleaning ~/.vimviews/"
  rm -Rf ~/.vimviews/*
  echo "Cleaning ~/.vimundo/"
  rm -Rf ~/.vimundo/*
  echo "All done!"
}


# Fix vagrant guest stuck at waiting for boot or waiting for graceful
# shutdown.
function forceVagrantShutdown() {
  # List available VMs
  VBoxManage list runningvms

  read -p "Which VM do you want to power off? " RESP

  VBoxManage controlvm $RESP poweroff

  echo "VM powered off. You shoud now be able run `vagrant up` sucessfully."
}

# Where a node version managed by `n` installed
export N_PREFIX="/usr/local"

# Use homebrew php on the command line..
export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

# Install casks in /Application instead of ~/Applications
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Use homebrew rbenv
export RBENV_ROOT="$(brew --prefix rbenv)"
export GEM_HOME="$(brew --prefix)/opt/gems"
export GEM_PATH="$(brew --prefix)/opt/gems"

export VISUAL='mvim -f'

# boost ulimit
ulimit -S -n 2048

# Load .zshrc.local if available, overrides other settings.
[[ -r ~/.zshrc.local ]] && . ~/.zshrc.local

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"
