# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="honukai"

# Auto start tmux
ZSH_TMUX_AUTOSTART=true

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(tmux gitfast zsh-syntax-highlighting osx brew z)

source $ZSH/oh-my-zsh.sh

# Force mkdir to create intermediate dirs
alias mkdir='mkdir -p'

# Stop auto correcting good commands!
alias vagrant='nocorrect vagrant'

# Force tmux to work with 256 colors.
alias tmux='tmux -2'

# Archiving
alias tarbz2='tar -jcvf'
alias targz='tar -zcvf'
alias untarbz2='tar -jxvf'
alias untargz='tar -zxvf'

# Git
alias gti='git'
alias gs='git status'
alias gc='git commit'
alias ga='git add'
alias gb='git branch'
alias gch='git checkout'
alias gl='git log --pretty=format:"%C(yellow)%h %C(blue)%ad%C(red)%d %C(reset)%s%C(green) [%cn]" --decorate --date=short'
alias yesterday="git log --since '1 day ago' --oneline --author nddery@gmail.com"

# Vim
# Start VIM in "encrypted" mode
alias vimenc="vim -u ~/.vimrc.encrypted -x"

# Update Brew packages (all)
alias brewUpdateAll="brew update --all && brew upgrade `brew outdated` && brew cleanup && brew cask cleanup"

# Let's go to nom!
alias nom='npm'

# exuberant ctags ftw
alias ctags="`brew --prefix`/bin/ctags"

# Remove those pesky .DS_Store files.
alias rmds="find . -name '*.DS_Store' -type f -delete"

# Install gems in the <cwd>/.bundle/ directory
alias bi="bundle install --path=.bundle"

# .mov to animated .gif!
# parameters are input output
function movtogif() {
  ffmpeg -i $1 -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=20 > $2
}

function movtocentral() {
  FILE=$(basename $1)
  rsync -avP $1 central@192.168.0.101:/Data/Public/Movies
  ssh central@192.168.0.101 'sudo chmod -R 0777 /Data/Public/Movies/$FILE'
}

# empty all VIM backup/swap/views directory (for when there's some problem
# with arrow keys and...)
function cleanVIM() {
  # directories we'll empty are
  echo "Cleaning ~/.vimbackup/"
  rm -Rf ~/.vimbackup/*
  echo "Cleaning ~/.vimswap/"
  rm -Rf ~/.vimswap/*
  echo "Cleaning ~/.vimviews/"
  rm -Rf ~/.vimviews/*
  echo "Cleaning ~/.vimundo/"
  rm -Rf ~/.vimundo/*
  echo "All done!"
}

# Where a node version managed by `n` installed
export N_PREFIX="/usr/local"

# Use homebrew php on the command line..
export PATH="$(brew --prefix homebrew/php/php70)/bin:$PATH"

# yarn.
export PATH="$PATH:$HOME/.yarn/bin"

# Install casks in /Application instead of ~/Applications
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Use homebrew rbenv
# export RBENV_ROOT="$(brew --prefix rbenv)"
# export GEM_HOME="$(brew --prefix)/opt/gems"
# export GEM_PATH="$(brew --prefix)/opt/gems"
eval "$(rbenv init -)"

# boost ulimit
ulimit -S -n 2048

# https://github.com/garabik/grc#automatic-aliases
[[ -s "/etc/grc.zsh"  ]] && source /etc/grc.zsh

# fzf
[ -f ~/.fzf.zsh  ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# export FZF_DEFAULT_OPTS='--height 40% --border'

# Load .zshrc.local if available, overrides other settings.
[[ -r ~/.zshrc.local ]] && . ~/.zshrc.local
