#!/bin/bash
source=`pwd`
bck_dir=$source.bck


G='\x1B[0;32m' # Green
C='\x1B[0;36m' # Cyan
NC='\x1B[0m' # No Color

dotfiles="zshrc vimrc.before.local vimrc.bundles.local vimrc.encrypted vimrc.local xvimrc tmux.conf"
preferences="com.apple.Terminal.plist"
brew="bar zsh tmux reattach-to-user-namespace caskroom/cask/brew-cask"


############
# Dotfiles #
############
echo -e "${C}Creating a backup of your dotfiles${NC}"
mkdir -p $bck_dir/dotfiles
for dotfile_bck in $dotfiles; do
  if [ -f ~/.$dotfile_bck ]
  then
    # Follow symlink
    cp -LR ~/.$dotfile_bck $bck_dir/dotfiles/$dotfile_bck
    # And remove the file
    rm ~/.$dotfile_bck
  fi
done

# And now symlink new dotfiles into place.
echo -e "${C}Copying new dotfiles into place${NC}"
for dotfile in $dotfiles; do
  ln -s $source/dotfiles/$dotfile ~/.$dotfile
done


###############
# Preferences #
###############
echo -e "${C}Creating a backup of your preferences${NC}"
mkdir -p $bck_dir/preferences
for preference_bck in $preferences; do
  if [ -f ~/Library/Preferences/$preference_bck ]
  then
    # Follow symlink
    cp -LR ~/Library/Preferences/$preference_bck $bck_dir/preferences/$preference_bck
    # And remove the file
    rm ~/Library/Preferences/$preference_bck
  fi
done

# And now symlink new preferences into place.
echo -e "${C}Copying new preferences into place${NC}"
for preference in $preferences; do
  cp -LR ~/Library/Preferences/$preference $bck_dir/preferences/$preference
  ln -s $source/preferences/$preference ~/Library/Preferences/$preference
done


#########
# Brew #
########
echo -e "${C}Brewing stuff${NC}"
for brew in $brews; do
  hash $brew &> /dev/null
  if [ $? -eq 1 ]; then
    echo -e "${C}Brewing $brew${NC}"
    brew install $brew
  else
    echo -e "${C}$brew already brewed${NC}"
  fi
done
# https://github.com/sindresorhus/quick-look-plugins
brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql qlimagesize webpquicklook suspicious-package


##########
# Others #
#########

# Install oh-my-zsh
cd ~
if [ ! -d .oh-my-zsh ]
then
  echo -e "${C}Installing oh-my-zsh${NC}"

  git clone git@github.com:robbyrussell/oh-my-zsh.git .oh-my-zsh

  if [ ! -f ~/.zshrc ]
  then
    cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
  fi
fi

# Install zsh-syntax-highlighting
cd ~/.oh-my-zsh/custom/
if [ ! -d plugins ]
then
  mkdir plugins
fi
cd plugins
if [ ! -d zsh-syntax-highlighting ]
then
  echo -e "${C}Enabling zsh-syntax-highlighting${NC}"
  git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
fi

# Set sensible OSX defaults.
echo -e "${C}Setting sensible OSX defaults${NC}"
sh $source/osx/defaults

# Change shell to zsh if not already like so
if [ $(echo $SHELL) != '/bin/zsh' ]
then
  echo -e "${C} Switching your login shell to use zsh${NC}"
  chsh -s /bin/zsh
fi

# Install tmux-vim-select-pane
# https://gist.github.com/mislav/5189704
if [ ! -f /usr/local/bin/tmux-vim-select-pane ]
then
  curl -fsSL https://raw.github.com/mislav/dotfiles/1500cd2/bin/tmux-vim-select-pane \
    -o /usr/local/bin/tmux-vim-select-pane
  chmod +x /usr/local/bin/tmux-vim-select-pane
fi

echo ""
echo -e "${G}----------------------------------------------------------------------"
echo ""
echo "                              All done!"
echo "You may want to install SPF13-Vim3 by running the 'updateVim' command."
echo ""
echo -e "----------------------------------------------------------------------${NC}"
echo ""
