#!/bin/bash

#
# Backup dot files and symlink the new ones into location
#

dest=~
source=`pwd`
bak=$source.bak

# list of files/folders to symlink
files="bash_profile vimrc.bundles.local vimrc.encrypted vimrc.local xvimrc tmux.conf"

# Backup everything
echo "Creating a backup of files"
mkdir -p $bak
for file in $files; do
  if [ -f $dest/.$file ]
  then
    # Follow symlink
    cp -LR $dest/.$file $bak/$file
    # And remove the file
    rm $dest/.$file
  fi
done

# And now symlink new files into place.
echo "Copying new files into place."
for file in $files; do
  ln -s $source/$file $dest/.$file
done

# Install spf13-vim
# curl http://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh

# Install bash completion
brew install bash-completion

# and set OSX defaults
#/bin/bash $dir/scripts/osx-set-defaults.sh

echo "All done!"
